name: Publish on docker hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get package version
        id: version
        run: echo "::set-output name=version::$(awk -F= '/^version/ { print $2 }' pyproject.toml | tr -d ' ' | tr -d '"')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            igormcsouza/talk2web:${{ steps.version.outputs.version }}
            igormcsouza/talk2web:latest
